# Generated by Django 5.2 on 2025-12-04 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('event_location', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('Indoor', 'Indoor Operations'), ('Outdoor', 'Outdoor Operations'), ('Hybrid', 'Hybrid Operations')], max_length=20)),
                ('event_created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_created_date'],
            },
        ),
        migrations.CreateModel(
            name='RtspTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('rtsp_url', models.CharField(max_length=500)),
                ('camera_location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sih_app.event')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
