# Generated by Django 5.2 on 2025-12-05 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelEnabled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_weapon_detection_enabled', models.BooleanField(default=False)),
                ('is_fire_detection_enabled', models.BooleanField(default=False)),
                ('is_face_covered_detection_enabled', models.BooleanField(default=False)),
                ('is_vechicle_detection_enabled', models.BooleanField(default=False)),
                ('is_suspicious_detection_enabled', models.BooleanField(default=False)),
                ('is_specific_object_detection_enabled', models.BooleanField(default=False)),
                ('is_face_recognition_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sih_app.event')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
