# Generated by Django 5.2 on 2025-12-05 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0002_aimodelenabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodelenabled',
            options={},
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.IntegerField()),
                ('detection_type', models.CharField(choices=[('face', 'Face Recognition'), ('object', 'Object Detection'), ('weapon', 'Weapon'), ('fire', 'Fire'), ('vehicle', 'Vehicle')], max_length=50)),
                ('detected_label', models.CharField(max_length=200)),
                ('confidence_score', models.FloatField()),
                ('bounding_box', models.JSONField(default=dict)),
                ('frame_snapshot', models.ImageField(blank=True, null=True, upload_to='detection_snapshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sih_app.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('face_image', models.ImageField(upload_to='face_database/')),
                ('face_embedding', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sih_app.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceRecognitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, unique=True)),
                ('model_file', models.FileField(upload_to='face_recognition_models/')),
                ('is_active', models.BooleanField(default=False)),
                ('confidence_threshold', models.FloatField(default=0.6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sih_app.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectDetectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, unique=True)),
                ('model_file', models.FileField(upload_to='object_detection_models/')),
                ('object_types', models.JSONField(default=list, help_text='List of detectable object types')),
                ('is_active', models.BooleanField(default=False)),
                ('confidence_threshold', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sih_app.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
