# Generated by Django 5.2 on 2025-12-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0003_alter_aimodelenabled_options_detectionlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtsptable',
            name='stream_type',
            field=models.CharField(choices=[('rtsp', 'RTSP Stream'), ('rtmp', 'RTMP Stream'), ('http', 'HTTP/HTTPS Stream'), ('hls', 'HLS Stream (M3U8)'), ('usb', 'USB Camera'), ('file', 'Video File'), ('ip', 'IP Camera (HTTP MJPEG)'), ('other', 'Other Protocol')], default='rtsp', max_length=20),
        ),
        migrations.AlterField(
            model_name='detectionlog',
            name='detection_type',
            field=models.CharField(choices=[('face', 'Face Recognition'), ('weapon', 'Weapon'), ('fire', 'Fire'), ('vehicle', 'Vehicle')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rtsptable',
            name='rtsp_url',
            field=models.CharField(help_text='Stream URL or device index for USB camera', max_length=500),
        ),
        migrations.DeleteModel(
            name='ObjectDetectionModel',
        ),
    ]
